# Generated by Django 3.2.3 on 2021-06-01 05:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('customer_address', models.CharField(max_length=100)),
                ('customer_city', models.CharField(max_length=50)),
                ('customer_car_no', models.CharField(max_length=20)),
            ],
        ),
    ]
