# Generated by Django 3.2.3 on 2021-06-01 13:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysyaraapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarWashOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('car_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Washer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('washer_shop_name', models.CharField(max_length=100)),
                ('current_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('is_available', models.BooleanField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='carwashorders',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='washer_name', to='mysyaraapp.washer'),
        ),
    ]
