# Generated by Django 3.2.3 on 2021-06-02 12:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysyaraapp', '0002_auto_20210601_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarWashOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('car_no', models.CharField(max_length=20)),
                ('assigned_to', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='washer_name', to='mysyaraapp.washer')),
            ],
        ),
        migrations.RemoveField(
            model_name='carwashorders',
            name='assigned_to',
        ),
        migrations.DeleteModel(
            name='CarWashOrders',
        ),
    ]
