# Generated by Django 3.2.3 on 2021-06-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysyaraapp', '0004_auto_20210602_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washer',
            name='is_available',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
